enum __attribute__((packed)) builtintheme {
    BITHEME_DEFAULT,
    BITHEME_COLORS,
    BITHEME_DOS,
    BITHEME_Matrix,
    BITHEME__COUNT
};
static const char* builtinthemenames[BITHEME__COUNT] = {
    "Default",
    "Colors",
    "DOS",
    "Matrix"
};
static struct drawcolor builtinthemes[BITHEME__COUNT][DCA__COUNT] = {
    {
        {.bold = 1, .underline = 1},
        {{0}},
        {.dim = 1},
        {.bold = 1, .underline = 1},
        {{0}},
        {.bold = 1},
        {{0}},
        {.bold = 1, .inverse = 1},
        {.inverse = 1},
        {{0}},
        {{0}},
        {.dim = 1},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {.strikethrough = 1},
        {.inverse = 1},
        {.inverse = 1},
        {.inverse = 1},
        {.inverse = 1}
    },
    {
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}}
    },
    {
        {.havefgc = 1, .fgc = 11, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 7, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 8, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 15, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 14, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 7, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 7, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 0, .havebgc = 1, .bgc = 7},
        {.havefgc = 1, .fgc = 7, .havebgc = 1, .bgc = 0},
        {.havefgc = 1, .fgc = 4, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 6, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 8, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 7, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 6, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 7, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 10, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 11, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 9, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 9, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 11, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 10, .havebgc = 1, .bgc = 4},
        {.havefgc = 1, .fgc = 0, .havebgc = 1, .bgc = 10},
        {.havebgc = 1, .bgc = 5},
        {.havebgc = 1, .bgc = 3},
        {.havebgc = 1, .bgc = 2},
        {.havebgc = 1, .bgc = 1}
    },
    {
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}},
        {{0}}
    }
};
